
"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { ServiceSchema, type FrpServiceInput, frpServiceTypes, FRP_SERVER_BASE_DOMAIN } from "@/lib/schemas";
import { useRouter } from "next/navigation";
import { useState, useEffect } from "react";
import { useToast } from "@/hooks/use-toast";
import { Loader2, Save } from "lucide-react"; // Removed Settings2 as Save is more appropriate for edit
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Info } from "lucide-react";


interface EditServiceFormProps {
  serviceId: string;
}

export default function EditServiceForm({ serviceId }: EditServiceFormProps) {
  const router = useRouter();
  const { toast } = useToast();
  const [isLoading, setIsLoading] = useState(false);
  const [isFetching, setIsFetching] = useState(true);

  const form = useForm<FrpServiceInput>({
    resolver: zodResolver(ServiceSchema),
    defaultValues: {
      name: "",
      description: "",
      localPort: '' as any, // Initialize with empty string
      subdomain: "",
      frpType: "http",
    },
  });

  useEffect(() => {
    setIsFetching(true);
    fetch(`/api/manager/service/${serviceId}`)
      .then(res => {
        if (!res.ok) throw new Error('Failed to fetch service details');
        return res.json();
      })
      .then((data: FrpServiceInput) => {
        form.reset({
            name: data.name,
            description: data.description,
            localPort: data.localPort === undefined || data.localPort === null ? '' : String(data.localPort) as any,
            subdomain: data.subdomain,
            frpType: frpServiceTypes.includes(data.frpType) ? data.frpType : "http",
        });
      })
      .catch(err => {
        toast({ title: "Error", description: err.message, variant: "destructive" });
        router.push("/dashboard");
      })
      .finally(() => setIsFetching(false));
  }, [serviceId, form, toast, router]);

  async function onSubmit(values: FrpServiceInput) {
    setIsLoading(true);
    try {
      const payload = {
        ...values,
        localPort: Number(values.localPort),
      };
      const response = await fetch(`/api/manager/service/${serviceId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      const data = await response.json();
      if (response.ok) {
        toast({ title: "Service Updated", description: `Service "${values.name}" tunnel updated successfully. You may need to restart your local frpc client with the new configuration.` });
        router.push("/dashboard");
      } else {
        toast({ title: "Update Failed", description: data.error || "Could not update service.", variant: "destructive" });
      }
    } catch (error) {
      toast({ title: "Update Error", description: "An unexpected error occurred.", variant: "destructive" });
    } finally {
      setIsLoading(false);
    }
  }

  const currentSubdomain = form.watch("subdomain");
  const publicUrlPreview = currentSubdomain ? `${currentSubdomain}.${FRP_SERVER_BASE_DOMAIN}` : `your-subdomain.${FRP_SERVER_BASE_DOMAIN}`;


  if (isFetching) {
    return (
      <div className="flex items-center justify-center py-10">
        <Loader2 className="mr-2 h-8 w-8 animate-spin text-primary" />
        <p>Loading service details...</p>
      </div>
    );
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-8">
        <Alert variant="default">
          <Info className="h-4 w-4" />
          <AlertTitle>Important Note on Editing</AlertTitle>
          <AlertDescription>
            Changes made here will update the configuration generated by PANDA.
            You will need to download the new <code className="font-mono bg-muted px-1 rounded">frpc.toml</code> file (via &quot;Get Config&quot; on the dashboard)
            and restart your local <code className="font-mono bg-muted px-1 rounded">frpc.exe</code> client for these changes to take effect.
            PANDA does not automatically update running frp clients.
          </AlertDescription>
        </Alert>

        <FormField
          control={form.control}
          name="name"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Service Name (for PANDA & Tunnel ID)</FormLabel>
              <FormControl>
                <Input placeholder="MyGameServer" {...field} />
              </FormControl>
              <FormDescription>A unique name for your service. Used in tunnel configuration. Allowed: letters, numbers, -, _</FormDescription>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="description"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Description</FormLabel>
              <FormControl>
                <Textarea placeholder="Brief description of your service (e.g., Minecraft Server, Personal Blog)." {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
         <div className="grid md:grid-cols-2 gap-8">
          <FormField
            control={form.control}
            name="localPort"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Local Port</FormLabel>
                <FormControl>
                  <Input
                    type="number"
                    placeholder="e.g., 3000 or 25565"
                    {...field}
                    value={field.value === undefined || field.value === null ? '' : String(field.value)}
                    onChange={e => field.onChange(e.target.value === '' ? '' : parseInt(e.target.value, 10))}
                  />
                </FormControl>
                <FormDescription>The port your service runs on locally.</FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />
          <FormField
            control={form.control}
            name="frpType"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Tunnel Type</FormLabel>
                <Select onValueChange={field.onChange} value={field.value}>
                  <FormControl>
                    <SelectTrigger>
                      <SelectValue placeholder="Select a tunnel type" />
                    </SelectTrigger>
                  </FormControl>
                  <SelectContent>
                    {frpServiceTypes.map((type) => (
                      <SelectItem key={type} value={type}>
                        {type.toUpperCase()}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <FormDescription>Protocol of your local service. For Minecraft, use TCP and port 25565.</FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />
        </div>
        <FormField
            control={form.control}
            name="subdomain"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Desired Subdomain</FormLabel>
                <FormControl>
                  <Input placeholder="mycoolservice" {...field} />
                </FormControl>
                <FormDescription>
                  Your service will be accessible at <code className="bg-muted px-1 py-0.5 rounded">{publicUrlPreview}</code>.
                  Use lowercase letters, numbers, and hyphens. This is used for HTTP/HTTPS and informative for other types.
                </FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />
        <Button type="submit" className="w-full sm:w-auto" disabled={isLoading || isFetching}>
          {(isLoading || isFetching) && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
          <Save className="mr-2 h-4 w-4" />
          Save Tunnel Changes
        </Button>
      </form>
    </Form>
  );
}
